-- Supabase Dashboard > SQL Editor에서 한 번 실행하세요.
-- 이 스키마는 "누구나 글을 올릴 수 있는" 수업용 공개 게시판을 전제로 합니다.
-- 공개 사이트이므로 민감한 정보는 게시하지 마세요.

create extension if not exists pgcrypto;

create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  author text not null default '' check (char_length(author) <= 80),
  department text not null default '' check (char_length(department) <= 100),
  body text not null default '' check (char_length(body) <= 12000),
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  entry_id uuid not null references public.entries(id) on delete cascade,
  voter_id uuid not null,
  created_at timestamptz not null default now(),
  unique (entry_id, voter_id)
);

alter table public.entries enable row level security;
alter table public.likes enable row level security;

drop policy if exists "Public can read entries" on public.entries;
create policy "Public can read entries"
on public.entries for select
to anon, authenticated
using (true);

drop policy if exists "Public can create entries" on public.entries;
create policy "Public can create entries"
on public.entries for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can read likes" on public.likes;
create policy "Public can read likes"
on public.likes for select
to anon, authenticated
using (true);

drop policy if exists "Public can create likes" on public.likes;
create policy "Public can create likes"
on public.likes for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can remove likes" on public.likes;
create policy "Public can remove likes"
on public.likes for delete
to anon, authenticated
using (true);

-- 공개 파일 저장소. Supabase SQL Editor에서는 storage 스키마를 사용할 수 있습니다.
insert into storage.buckets (id, name, public, file_size_limit)
values ('entry-media', 'entry-media', true, 52428800)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

drop policy if exists "Public can view entry media" on storage.objects;
create policy "Public can view entry media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'entry-media');

drop policy if exists "Public can upload entry media" on storage.objects;
create policy "Public can upload entry media"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'entry-media');

-- 선택 사항: 운영자가 Dashboard에서 직접 게시물/파일을 삭제할 수 있습니다.
-- 브라우저에는 service_role 키를 절대 노출하지 마세요.
